services:
  cert-signer:
    image: cert-signer:latest
    ports:
      - "3000:3000"
    volumes:
      - ./certs:/app/certs
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy-config:/config
      - caddy-data:/data

volumes:
  caddy-config:
  caddy-data:
